# version: "3"

services:
  postgres_db:
    container_name: auth_service-postgres_db
    build:
      context: "./.docker/postgresql"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB_NAME: ${POSTGRES_DB_NAME}
      POSTGRES_USER_NAME: ${POSTGRES_USER_NAME}
      POSTGRES_USER_PASSWORD: ${POSTGRES_USER_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
    driver: local
# networks:
#   default:
#     name: custom_net
#     external: true
